spring:
  application:
    name: Helpdesk

  datasource:
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: sa
    password: ""

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    error:
      include-stacktrace: never